// Liepin Auto-Apply · Automation-run setup helper (v1.2.0)
// Zero external deps: only Node stdlib fs/path
// Role: read liepin_wizard_config.json; when unattended=true, generate a
//       WorkBuddy periodic automation (automation) spec for the AI agent to register via automation_update,
//       achieving "zero-touch" scheduled auto-delivery.
//
// Usage (run by the AI agent):
//   node scripts/setup_automation.js
// The script writes liepin_automation_spec.json and prints the registration hint for the agent.

'use strict';
const fs = require('fs');
const path = require('path');

const WORKDIR = process.cwd();
const CONFIG_PATH = path.join(WORKDIR, 'liepin_wizard_config.json');
const SPEC_PATH = path.join(WORKDIR, 'liepin_automation_spec.json');

// Best-effort mapping cron(5-field) -> WorkBuddy RRULE (RFC5545)
function cronToRRule(cron) {
  const p = String(cron || '').trim().split(/\s+/);
  if (p.length !== 5) return null;
  const [min, hour, dom, mon, dow] = p;
  if (hour === '*' && dom === '*' && mon === '*' && dow === '*') {
    // Every N hours: 0 */6 * * *  -> FREQ=HOURLY;INTERVAL=6
    if (min !== '*' && /^(?:\*\/)?\d+$/.test(min)) {
      const m = min.startsWith('*/') ? min.slice(2) : min;
      return `FREQ=HOURLY;INTERVAL=${m}`;
    }
    return 'FREQ=HOURLY;INTERVAL=6';
  }
  // Daily at a time: 0 9 * * * -> FREQ=DAILY;BYHOUR=9;BYMINUTE=0
  const hh = parseInt(hour, 10);
  const mm = parseInt(min, 10);
  if (!isNaN(hh) && dom === '*' && mon === '*' && dow === '*') {
    return `FREQ=DAILY;BYHOUR=${hh};BYMINUTE=${isNaN(mm) ? 0 : mm}`;
  }
  return null; // complex cron left for the agent to build manually
}

function main() {
  if (!fs.existsSync(CONFIG_PATH)) {
    console.error('Missing liepin_wizard_config.json (please complete the popup wizard to collect criteria first)');
    process.exit(3);
  }
  const cfg = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8'));
  if (cfg.unattended !== true) {
    console.log('ℹ️  Current config has "unattended" disabled (unattended=false).');
    console.log('   To set up automation: go back to wizard step 7 and choose "Enable unattended", or set unattended=true in config, then rerun this script.');
    process.exit(0);
  }

  const cron = cfg.schedule || '0 9 * * *';
  const rrule = cronToRRule(cron) || 'FREQ=DAILY;BYHOUR=9;BYMINUTE=0';
  const cap = cfg.dailyCap && cfg.dailyCap < 999 ? cfg.dailyCap : 50;

  const spec = {
    name: 'Liepin Auto-Apply (Unattended)',
    scheduleType: 'recurring',
    rrule: rrule,
    cwds: WORKDIR,
    prompt:
      `Read workspace liepin_wizard_config.json; if unattended=true and Token is configured (LIEPIN_USER_TOKEN or ~/.config/liepin-cli/config.json), directly run ` +
      '`node scripts/apply_pipeline.js` (no popup confirmation, zero touch);' +
      `After run, read liepin_wizard_summary.md and report to the user in one line the success/fail/already-applied counts.` +
      `If Token is missing or config absent, only report the reason in text, no unauthorized action.`,
    note: `This automation is generated by the "Liepin Fully-Automated Resume Delivery" skill; daily cap ${cap}, guarded by rate-limit / circuit-break.`,
  };

  fs.writeFileSync(SPEC_PATH, JSON.stringify(spec, null, 2), 'utf8');

  console.log('✅ Automation spec generated: ' + SPEC_PATH);
  console.log('--- spec ---');
  console.log(JSON.stringify(spec, null, 2));
  console.log('--- registration hint for the AI agent ---');
  console.log('Please register the above periodic automation with automation_update (mode=create):');
  console.log('  name   =', spec.name);
  console.log('  rrule  =', spec.rrule, '(from config schedule:', cron + ')');
  console.log('  cwds   =', spec.cwds);
  console.log('  prompt =', spec.prompt);
}

main();
